[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "client"

[[bin]]
name = "server"


[dependencies]
gl = "0.14.0"
glfw = "0.61.0"
image = "0.25.9"
macros = { path = "macros"}